template: |
  ## リリースサマリ
  $CHANGES

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
categories:
  - title: 🚀 Features
    labels: [feature, enhancement]
  - title: 🐛 Fixes
    labels: [bug, fix]
  - title: 🧰 Maintenance
    labels: [chore, maintenance]
