name: Governance Gate

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: '3.11'
  pull_request:
    types: [opened, edited, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  governance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event_name == 'workflow_call' && inputs.python-version || '3.11' }}
      - name: Governance gate
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: python tools/ci/check_governance_gate.py
