name: Sync labels

on:
  push:
    paths:
      - .github/labels.yml
      - .github/workflows/labels-sync.yml
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      metadata: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Synchronize labels
        uses: github/labels@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labels.yml
