name: markdown-quality
on:
  pull_request:
  push:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Check front matter
        run: python tools/ci/check_front_matter.py --check
      - uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          globs: |
            **/*.md
      - name: Run Vale
        uses: errata-ai/vale-action@v2
        continue-on-error: true
