name: Security Gate

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  security-ci:
    uses: ./.github/workflows/reusable/security-ci.yml
    permissions:
      contents: read
      security-events: write
    secrets: inherit
